language: python
python:
- '2.7'
- '3.5'
- '3.6'
- 3.6-dev
- 3.7-dev
install:
- pip install -r requirements.txt
script:
- python -m unittest discover -s piservopantilt/tst/
deploy:
  provider: pypi
  user: kangasta
  password:
    secure: dlUzeXdPwCVxS483pgFIwt6YVKfFBoA4Zi/aC5nMLHzOq95MgvXFi/a4eB4B8bHDIP/lO7SCZfjGbPteMKRKliTGlh5F1sYbLcw394DH9B/KayNjlzWzR+SbGFDtTJc0z/AnHferyruhp/nYYO13UL9j50ZxoC5jKS87hHsibMkdwBVfckQYDeqFeF2lVEA847tkB68cYrvD6y5m9kleYTAofqqNlPdQKO4yVHy64pKP2z6ZOw+dKwB8xhkYaWYPYtgO9cb+2LpVx2Go0FbDd/1YxeGgQfwHUMfG0tmKGdGcsO6xNRqQptEmMQhMzDtVLBdOx86k+NvDPJr5Q/mae3BIS2qRMhGcQr8jpn8AFKTVeWZO/2n9haWk9Ct1zOebju2LQZ4xjNuAbUeepwi2WPp/IXz7YuOa9Ga5tPnMdXuZ1gJT2R0iUb1pknCrjLKMtOwwOZXpAcMYLKN3uotfXDEfPUxrhm44rNacef8HC0AlYK4p8iN+35/dWC7FDccSfTUVMXroHQi1hKrMsVxkVTa6UlaNSsLjQpLopjlWlV9uysPESZoLz0ET+C4ZkhMdH0xwbT/DJhfT+NeK25REezMqCO2+QHJyjD+3CA3LBTTViEHRdsjuSB3Hn98y0WheO8lTWbfcG0RSnOUmOk7gy6C+JjM5TNkk5V0V/gU18IU=
  on:
    tags: true
